[font]
size = 10.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "tmux"

[window]
opacity = 0.9

[terminal]

[keyboard]
bindings = [
    { key = "=", mods = "Control", action = "ResetFontSize" },
    { key = "+", mods = "Shift|Control", action = "IncreaseFontSize" },
    { key = "-", mods = "Control", action = "DecreaseFontSize" },
]

[general]
import = [ "~/.config/alacritty/dark_theme.toml" ]
