#!/bin/bash

sudo pacman -S \
    alacritty \
    neovim \
    git \
    stow \
    tmux \
    trash-cli \
    openssh \
    polkit-kde-agent \
    greetd-tuigreet \
    ttf-hack-nerd \
    udisks2 \
    zsh \
    dunst \
    man \


sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && cd .. && rm -rf yay

sudo systemctl enable greetd
sudo sed -i 's/^command.*$/command = "tuigreet --cmd sh"/g' /etc/greetd/config.toml
chsh -s $(which zsh)

stow base
