#!/bin/bash

sudo pacman -S \
    hyprland \
    waybar \
    swww \
    xdg-desktop-portal-hyprland \
    grim \
    slurp \
    wl-clipboard \
    hyprlock \
    hypridle \
    rofi-wayland \
    dunst \

sudo sed -i 's/^command.*$/command = "tuigreet --cmd start-hyprland"/g' /etc/greetd/config.toml

stow hyprland
