#!/bin/bash

sudo pacman -S \
    zathura \
    zathura-pdf-mupdf \
    firefox \
    ncdu \
    imv \
    mpv \
    lf \
    perl-file-mimeinfo \
    fzf \
    ripgrep \
    tldr \
    man \

stow extra
