#!/bin/bash

sudo pacman -S \
    zathura \
    zathura-pdf-mupdf \
    firefox \
    ncdu \
    imv \
    mpv \
    lf \
    perl-file-mimeinfo \
    fzf \
    ripgrep \
    tldr \
    blender freecad inkscape krita \
    discord \
    bitwarden \
    brightnessctl \
    entr \
    htop nvtop \
    piper \
    pulsemixer \
    steam minecraft-launcher \
    unrar unzip \
    wget \

stow extra
