# Colors
$RED          = rgba(FF3333EE)
$RED_DARK     = rgba(960000EE)
$SHADOW       = rgba(1A1A1AEE)
$GRAY         = rgba(383838AA)
$GRAY_LIGHT   = rgba(CDD6F4AA)
$WHITE        = rgba(FFFFFFFF)
$GRAY_LIGHTER = rgba(EFF8F6AA)
$WHITE_DARK   = rgba(888888AA)

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    col.active_border = $RED $RED_DARK 45deg
    col.inactive_border = $GRAY

    layout = master
}

decoration {
    rounding = 2

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = $SHADOW
    }
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

animations {
    enabled = yes

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 1, myBezier
    animation = windowsOut, 1, 1, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 1, default
    animation = workspaces, 1, 1, default
}

group {
    col.border_active = $RED $RED_DARK 45deg
    col.border_inactive = $GRAY
    col.border_locked_active = $RED
    col.border_locked_inactive = $GRAY

    groupbar {
        font_size = 12
        font_weight_active = normal
        font_weight_inactive = normal
        height = 16
        indicator_height = 3
        text_offset = 2
        text_padding = 8

        text_color = $WHITE
        text_color_inactive = $GRAY_LIGHTER
        text_color_locked_active = $WHITE
        text_color_locked_inactive = $GRAY_LIGHT

        col.active = $RED
        col.inactive = $WHITE_DARK
        col.locked_active = $RED_DARK
        col.locked_inactive = $GRAY
    }

}
